controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    # 关节状态控制器
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 麦克纳姆轮驱动控制器
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController


mecanum_drive_controller:
  ros__parameters:
    # 命令超时时间（秒）
    reference_timeout: 0.3
    
    # 轮子命令关节名称 - 必须与URDF中的joint名称一致
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_right_wheel_joint"
    
    # 运动学配置
    kinematics:
      # 机器人中心相对于轮子几何中心的偏移
      # 您的机器人中心在base_link原点，轮子几何中心也在原点
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      # 轮子半径（米）
      wheels_radius: 0.05
      # X轴和Y轴投影之和 = Lx/2 + Ly/2 = 0.19 + 0.22 = 0.41
      sum_of_robot_center_projection_on_X_Y_axis: 0.41
    
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    enable_odom_tf: true
    publish_rate: 30.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.01, 0.01, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.01, 0.01, 0.01]


    # # 差速控制器
    # diff_drive_controller:
    #   type: diff_drive_controller/DiffDriveController
    #   left_wheel_names:
    #     - front_left_wheel_joint
    #     - rear_left_wheel_joint
    #   right_wheel_names:
    #     - front_right_wheel_joint
    #     - rear_right_wheel_joint
    #   cmd_vel_timeout: 0.5
    #   wheel_separation: 0.4  # 轮间距，单位：米
    #   wheel_radius: 0.05     # 轮半径，单位：米
    #   publish_rate: 50       # 发布频率，单位：Hz

    # velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController
    #   joints:
    #     - front_left_wheel_joint
    #     - front_right_wheel_joint
    #     - rear_left_wheel_joint
    #     - rear_right_wheel_joint